### ISSUE TITLE
dataset json file does not go with image names

### ISSUE THREAD

**Issue by Philliec459** [SriRamGovardhanam/wastedata-Mask_RCNN-multiple-classes#3]
your json files in dataset do not go with the images???

**Comment by SriRamGovardhanam** [comment]
Hii @Philliec459 , sorry for the late reply
I intentionally provided few images in the Repo, because the original image data in not mine while the json labelling was done by me.
Anyway the main purpose of this repo is to make your own model for multiple classes.
